# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

phpunit-template: &phpunit-template
  steps:
    - checkout
    - run: apt-get update && apt-get install -y $PHPIZE_DEPS libzip-dev unzip libzip4 &&
        mkdir -p /usr/src/php/ext/pcov && curl -fsSL https://pecl.php.net/get/pcov | tar xvz -C "/usr/src/php/ext/pcov" --strip 1 &&
        docker-php-ext-install -j$(nproc) pcov zip
    - run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - run: composer install
    - run: php vendor/bin/phpunit --coverage-text=php://stdout

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  phpunit-8-0:
    <<: *phpunit-template
    docker:
      - image: php:8.0

  phpunit-8-1:
    <<: *phpunit-template
    docker:
      - image: php:8.1

  stan:
    docker:
      - image: cacahouete/phpaudit
    steps:
      - checkout
      - run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - run: composer install
      - run: phpstan analyse
  cs:
    docker:
      - image: cacahouete/phpaudit
    steps:
      - checkout
      - run: "php-cs-fixer fix --dry-run --using-cache=no --verbose --diff"
  cpd:
    docker:
      - image: cacahouete/phpaudit
    steps:
      - checkout
      - run: "phpcpd src"
  md:
    docker:
      - image: cacahouete/phpaudit
    steps:
      - checkout
      - run: "phpmd src text .phpmd.xml"

workflows:
  TESTS:
    jobs:
      - phpunit-8-0
      - phpunit-8-1
      - stan
      - cs
      - cpd
      - md
